webapp:
  build: .
  volumes:
    - "./assets:/data/larmo-webapp/assets"
    - "./views:/data/larmo-webapp/views"
    - "./.git:/data/larmo/.git"
  ports:
    - "5000:8080"
  environment:
    - API_URL=http://0.0.0.0:5100
